/*  Tabela Data, Prefixo e Km Negativo*/
SELECT DATA, PREFIXO,  SUM(HODFINALVELOC - HODINICIALVELOC) AS Km_Negativo

FROM fact_vwpbi_abastecimento_detalhado where data >= '2025-01-01 00:00:00'
AND (HODFINALVELOC - HODINICIALVELOC) < 0

GROUP BY DATA, PREFIXO, (HODFINALVELOC - HODINICIALVELOC)
ORDER BY DATA ASC