-- Colunas mais usadas Gt Frotas
SELECT  EMPRESA, HAS_DATA, VEI_IDENTIFICACAO_EMPRESA, 
HAS_QTD_LITROS, KM_PERCO, KM_ANT, HAS_ODOMETRO,  HAS_ENCERRANTE_ANTES, HAS_ENCERRANTE_DEPOIS
 
 FROM fact_vwpbi_abast_gtfrota  WHERE HAS_DATA >= '2025-01-01 00:00:00' 
 ORDER BY HAS_DATA ASC