/* Inconsistência na quantidade de Litros*/

SELECT * FROM (
  SELECT 
    HAS_DATA, EMPRESA, VEI_IDENTIFICACAO_EMPRESA, HAS_QTD_LITROS, 
    (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) AS RECALCULA_QTD,

    CASE 
      WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) = HAS_QTD_LITROS THEN 'OK' ELSE 'ERRO' 
    END AS CheckList,

	(VEI_LIMITE_ABASTECIMENTO - HAS_QTD_LITROS)AS Volume_Excedente,

    VEI_LIMITE_ABASTECIMENTO,(HAS_ODOMETRO - KM_ANT ) AS RECALCULA_KM,HAS_ENCERRANTE_ANTES, 
    HAS_ENCERRANTE_DEPOIS, HAS_ODOMETRO, KM_ANT, KM_PERCO

  FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00'
) AS sub

WHERE  Volume_Excedente < 0 
/*AND
  NOT (
  HAS_QTD_LITROS = 0 AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) IS NULL
)
*/

