-- QTD Abastecimento sem deslocamento
SELECT 
    count(HAS_QTD_LITROS)
FROM fact_vwpbi_abast_gtfrota
WHERE 
    HAS_DATA >= '2025-01-01 00:00:00'
    AND (KM_PERCO = 0 OR KM_PERCO = -110)
    AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) IS NOT NULL
    AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) <> 0
    AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) <> 0.01;
