SELECT 
    EMPRESA,
    CASE WHEN EMPRESA = 27 THEN 'Pernambuco' ELSE 'São Paulo' END AS Empresa,
    VEI_IDENTIFICACAO_EMPRESA AS Prefixo, 
    VEI_LIMITE_ABASTECIMENTO AS Tanque
   
FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' 
GROUP BY EMPRESA, VEI_IDENTIFICACAO_EMPRESA
ORDER BY Prefixo;