SELECT 
    EMPRESA,
    CASE WHEN EMPRESA = 27 THEN 'Pernambuco' ELSE '' END AS Empresa,
    VEI_IDENTIFICACAO_EMPRESA AS Prefixo, 
    MAX(VEI_LIMITE_ABASTECIMENTO) AS Tanque,
    MAX(HAS_QTD_LITROS) AS Litros
FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' AND EMPRESA = 27
GROUP BY EMPRESA, VEI_IDENTIFICACAO_EMPRESA
ORDER BY Prefixo;
