-- Média Litros Duplicados 

SELECT 
    ROUND(AVG(HAS_QTD_LITROS),2) AS MEDIA_LITROS_DUPLICADOS
FROM (
    SELECT 
        EMPRESA,
        DATE(HAS_DATA) AS DATA_SEM_HORA,
        VEI_IDENTIFICACAO_EMPRESA,
        HAS_QTD_LITROS
    FROM fact_vwpbi_abast_gtfrota
    WHERE HAS_DATA >= '2025-01-01 00:00:00' AND HAS_QTD_LITROS >= 0.01
    GROUP BY EMPRESA, DATE(HAS_DATA), VEI_IDENTIFICACAO_EMPRESA, HAS_QTD_LITROS
    HAVING COUNT(*) >= 2
) AS Duplicados;


