-- Soma Litros Duplicados GT Frotas para HAS_QTD_LITROS 
SELECT 
   ROUND( SUM(Litros) ,2)AS TOTAL_LITROS_DUPLICADOS
FROM (
    SELECT 
        EMPRESA AS Empresa, DATE(HAS_DATA) AS Data, 
        VEI_IDENTIFICACAO_EMPRESA AS Prefixo, HAS_QTD_LITROS AS Litros
    FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' 
    GROUP BY EMPRESA, DATE(HAS_DATA), VEI_IDENTIFICACAO_EMPRESA, HAS_QTD_LITROS
    HAVING COUNT(*) >= 2
) AS Duplicados;

/* 05/08 = 1904.53 L
   07/08 = 1964.63L*/