-- Soma Litros Duplicados GT Frotas para Recalcula HAS_QTD_LITROS

SELECT 
    SUM(Litros) AS Total_Litros_Duplicados
FROM (
    SELECT 
        ROUND((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES),1) AS Litros, 
        COUNT(*) AS QTD
    FROM fact_vwpbi_abast_gtfrota
    WHERE HAS_DATA >= '2025-01-01 00:00:00' AND HAS_ENCERRANTE_DEPOIS IS NOT NULL AND HAS_ENCERRANTE_ANTES IS NOT NULL
    GROUP BY EMPRESA, DATE(HAS_DATA), VEI_IDENTIFICACAO_EMPRESA, ROUND((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES),1)
    HAVING COUNT(*) >= 2
) AS duplicados;
