-- Soma Litros Duplicados GT Frotas para HAS_QTD_LITROS

SELECT 
   ROUND(SUM(Litros), 2) AS TOTAL_LITROS_DUPLICADOS
FROM (
    SELECT  EMPRESA, DATE(HAS_DATA) AS DATA_SEM_HORA, VEI_IDENTIFICACAO_EMPRESA AS PREFIXO, 
    ROUND(HAS_QTD_LITROS, 2) AS Litros
    FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' AND HAS_QTD_LITROS >= 0.01
    GROUP BY 
        EMPRESA, DATE(HAS_DATA), VEI_IDENTIFICACAO_EMPRESA, 
        ROUND(HAS_QTD_LITROS, 2)
    HAVING COUNT(*) >= 2
) AS Duplicados;
