-- Colunas mais usadas Gt Frotas para Dashboards de abastecimento Manual

SELECT  EMPRESA, HAS_DATA AS DATA, VEI_IDENTIFICACAO_EMPRESA AS Prefixo , 
ROUND((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES),1) AS RecalculaLitros, 
HAS_QTD_LITROS,(HAS_ODOMETRO - KM_ANT) AS RecalculaKm , 
 BOM_CODIGO, CAR_CODIGO_ABASTECEDOR,VEI_CODIGO, TER_DATA_ULTIMA_COMUNIC
 
 FROM fact_vwpbi_abast_gtfrota  WHERE HAS_DATA >= '2025-01-01 00:00:00' 
 ORDER BY HAS_DATA ASC