--  Gera coluna que compara a coluna de Qtd_Litros com a recalculada
/* Calcular novamente a difereça entre o encerrante antes e depois para
saber se o valor bate com HAS_QTD_LITROS*/

SELECT VEI_IDENTIFICACAO_EMPRESA AS PREFIXO,
HAS_DATA AS DATA, EMPRESA, HAS_QTD_LITROS, ABS(HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) AS Recalcula_QTD_LITROS ,
 HAS_ENCERRANTE_DEPOIS, HAS_ENCERRANTE_ANTES,
 
CASE 

WHEN HAS_ENCERRANTE_DEPOIS IS NULL OR HAS_ENCERRANTE_ANTES IS NULL THEN 'NULL'
WHEN HAS_ENCERRANTE_DEPOIS = 0 OR HAS_ENCERRANTE_ANTES = 0 THEN '0'
WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES  ) = HAS_QTD_LITROS THEN '' ELSE 'ERROR'
END AS Verifica

FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' 

