-- Prefixo que mais e menos abasteceu sem deslocamento Gt Frota
SELECT 
    VEI_IDENTIFICACAO_EMPRESA AS PREFIXO,  
    ROUND(SUM(HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES), 2) AS Litros
FROM fact_vwpbi_abast_gtfrota
WHERE HAS_DATA >= '2025-01-01 00:00:00' AND KM_PERCO = 0 AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) <> 0
GROUP BY VEI_IDENTIFICACAO_EMPRESA
ORDER BY Litros DESC;
