-- Tabela Consumo Prefixo Abas sem Deslocamento Gt Frota 
SELECT 
    HAS_DATA AS DATA,
    CASE 
        WHEN EMPRESA = 21 THEN 'São Paulo'
        WHEN EMPRESA = 27 THEN 'Pernambuco'
        ELSE NULL
    END AS Empresas,
    VEI_IDENTIFICACAO_EMPRESA AS PREFIXO,(HAS_ODOMETRO - KM_ANT) AS KMPercorrido,
    (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) AS Litros, VEI_LIMITE_ABASTECIMENTO
   
FROM fact_vwpbi_abast_gtfrota
WHERE 
    HAS_DATA >= '2025-01-01 00:00:00'
    AND (HAS_ODOMETRO - KM_ANT) = 0 AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) IS NOT NULL
    AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) <> 0
ORDER BY HAS_DATA ASC;
