-- Soma dos Litros Recalculados e HAS_QTD_LITROS

SELECT   
ROUND(SUM((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES)),1) AS RecalculaLitros, 
ROUND(SUM(HAS_QTD_LITROS),2) AS HAS_QTD_LITROS, 
( ROUND(SUM((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES)),1) - ROUND(SUM(HAS_QTD_LITROS),2) ) AS Diferença

 FROM fact_vwpbi_abast_gtfrota  WHERE HAS_DATA >= '2025-01-01 00:00:00' 
 ORDER BY HAS_DATA ASC