-- Selecionando tudo que for importante para o Km Globus recalculando o Km e gerando coluna de status

SELECT DATA, EMPRESA, PREFIXO, HODINICIALVELOC, HODFINALVELOC, KMPERCORRIDO,
ROUND((HODFINALVELOC - HODINICIALVELOC),3) AS KmRecalculado,
ROUND(ABS(HODFINALVELOC - HODINICIALVELOC) - KMPERCORRIDO, 2) AS Diferenca,

CASE WHEN ROUND((HODFINALVELOC - HODINICIALVELOC),3) <> KMPERCORRIDO THEN 'Divergente' ELSE '' 
END AS StatusKm,
LITROS, CONSUMO,  TIPO_FROTA, VALOR, LINHA
FROM fact_vwpbi_abastecimento_detalhado WHERE DATA >= '2025-01-01 00:00:00'