-- Soma Volume Excedente Litros Litros calculados (66,95)
SELECT 
  ROUND(
    SUM(
      ROUND((HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) - VEI_LIMITE_ABASTECIMENTO, 2)), 2
  ) AS SOMA_Volume_Excedente
FROM fact_vwpbi_abast_gtfrota
WHERE HAS_DATA >= '2025-01-01 00:00:00'
  AND (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) > VEI_LIMITE_ABASTECIMENTO;