-- Mostra os Km Negativos
SELECT 
  HAS_DATA, VEI_IDENTIFICACAO_EMPRESA AS PREFIXO, KM_ANT, HAS_ODOMETRO, KM_PERCO, (HAS_ODOMETRO - KM_ANT) AS Recalcula_Km
,
CASE
when KM_PERCO < 0 THEN 'Negativo' else ' '
END AS Comparacao

FROM 
  fact_vwpbi_abast_gtfrota
WHERE 
  HAS_DATA >= '2025-01-01 00:00:00'
ORDER BY 
  HAS_DATA, VEI_IDENTIFICACAO_EMPRESA, KM_ANT,  HAS_ODOMETRO,  KM_PERCO, (HAS_ODOMETRO - KM_ANT) ;
