-- Recalcula Litros

SELECT VEI_IDENTIFICACAO_EMPRESA AS PREFIXO,
EMPRESA, VEI_LIMITE_ABASTECIMENTO, HAS_QTD_LITROS, ABS(HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES ) AS Recalcula_QTD_LITROS
,
CASE 

WHEN (HAS_ENCERRANTE_DEPOIS IS NULL OR HAS_ENCERRANTE_ANTES IS NULL) AND HAS_QTD_LITROS THEN ''  /* Casos aonde um dos valores é NULL*/
WHEN (HAS_ENCERRANTE_DEPOIS = 0 OR HAS_ENCERRANTE_ANTES = 0) AND THEN '0'             /* Casos aonde um dos valores é zero*/
WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) IS NULL  AND HAS_QTD_LITROS = 0 THEN '' /* Casos aonde a conta é zero e o HAS_QTD é null*/
WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) = HAS_QTD_LITROS THEN '' ELSE 'ERROR'
END AS VerificaLitros

FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' 
