-- Recalcula Litros

SELECT VEI_IDENTIFICACAO_EMPRESA AS PREFIXO,
EMPRESA, VEI_LIMITE_ABASTECIMENTO, HAS_QTD_LITROS, ABS(HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES ) AS Recalcula_QTD_LITROS,

CASE 

WHEN (HAS_ENCERRANTE_DEPOIS IS NULL OR HAS_ENCERRANTE_ANTES IS NULL) AND HAS_QTD_LITROS = 0 THEN ''  /* Casos aonde um dos valores é NULL*/
/* Não pega assim: WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) IS NULL  AND HAS_QTD_LITROS = 0 THEN '0' */

WHEN (HAS_ENCERRANTE_DEPOIS = 0 OR HAS_ENCERRANTE_ANTES = 0) AND HAS_QTD_LITROS = 0 THEN ''             /* Casos aonde um dos valores é zero*/

WHEN (HAS_ENCERRANTE_DEPOIS - HAS_ENCERRANTE_ANTES) = HAS_QTD_LITROS THEN '' ELSE 'ERROR'
END AS VerificaLitros
,HAS_ENCERRANTE_DEPOIS ,HAS_ENCERRANTE_ANTES 

FROM fact_vwpbi_abast_gtfrota WHERE HAS_DATA >= '2025-01-01 00:00:00' 
